services:
  aabot:
    build: 
      context: ./aabot
      args:
        IMAGE_NAME: aabot
    env_file:
      - .env
    volumes:
      - type: volume
        source: mementodb
        target: /usr/src/app/data
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "50m"
    restart: unless-stopped
    
volumes:
  mementodb:
    name: mementodb
