services:
  aabot:
    image: ${IMAGE_NAME}
    env_file:
      - .env
    volumes:
      - type: volume
        source: mementodb
        target: /usr/src/app/data
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
    restart: on-failure
    
volumes:
  mementodb:
    name: mementodb
