services:
  aabot:
    build: 
      context: ./aabot
      args:
        IMAGE_NAME: aabot
    env_file:
      - .env
    volumes:
      - ./aabot:/app/aabot
      - ./common:/app/common
    logging:
      options:
        max-file: "2"
        max-size: "50m"
    restart: unless-stopped
    networks:
      - aa-network
    depends_on:
      - postgres

  api:
    build:
      context: ./api
      args:
        IMAGE_NAME: aabot-api
    env_file:
      - .env
    volumes:
      - ./api:/app/api
      - ./common:/app/common
    restart: unless-stopped
    networks:
      - aa-network
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - aa-network

  nginx:
    image: nginx
    restart: unless-stopped
    profiles:
      - prd
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - aa-network

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    profiles:
      - prd
    depends_on:
      - nginx
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"
    networks:
      - aa-network

  nginx-local:  # local testing profile
    image: nginx
    restart: unless-stopped
    profiles:
      - local
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-local.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    networks:
      - aa-network

volumes:
  postgres-data:
    name: postgres-data
    driver: local

networks:
  aa-network:
    driver: bridge
