API_BASE_PATH = "http://api:8000"

ARCANA_PATH = "/arcana/{char_id}"
ARCANA_SEARCH_PATH = "/arcana/search"
CHARACTER_SEARCH_PATH = "/character/search"
CHARACTER_INFO_PATH = "/character/info/{char_id}"
CHARACTER_PROFILE_PATH = "/character/profile/{char_id}"
CHARACTER_LAMENT_PATH = "/character/lament/{char_id}"
CHARACTER_SKILL_PATH = "/character/skill/{char_id}"
CHARACTER_VOICE_PATH = "/character/voiceline/{char_id}"
CHARACTER_MEMORY_PATH = "/character/memory/{char_id}"
CHARACTER_ALTS_PATH = "/character/alts"
CHARACTER_ALTS_ID_PATH = "/character/alts/{char_id}"
CHARACTER_POTENTIAL_PATH = "/character/potential"
ITEM_PATH = "/item/search"
ITEM_RUNE_PATH = "/item/rune"
ITEM_RUNE_CATEGORY_PATH = "/item/rune/{category}"
EQUIPMENT_PATH = "/equipment/{eqp_id}"
EQUIPMENT_SEARCH_PATH = "/equipment/search"
EQUIPMENT_UW_SEARCH_PATH = "/equipment/unique/search"
EQUIPMENT_UPGRADE_PATH = "/equipment/upgrade"
MASTER_PATH = "/master/{mb}"
GACHA_PATH = "/gacha"
QUEST_PATH = "/quest/{quest_id}"
SKILL_PATH = "/skill/{skill_id}"
STRING_PATH = "/strings/lookup/{key}"
STRING_CHARACTER_PATH = "/strings/character"
STRING_CHARACTER_ID_PATH = "/strings/character/{char_id}"
STRING_UW_DESC_PATH = '/strings/uw_descriptions/{char_id}'
STRING_COMMON_PATH = "/strings/common"
TOWER_PATH = "/tower"

# Admin
UPDATE_PATH = "/admin/update"
UPDATE_STR_PATH = "/admin/update/strings"
UPDATE_CHAR_PATH = "/admin/update/characters"
UPDATE_MENTEMORI_PATH = "/admin/mentemori"
UPDATE_API_PLAYERS_PATH = "/admin/mentemori/players"
UPDATE_API_GUILD_PATH = "/admin/mentemori/guilds"
RESET_ALT_PATH = "/admin/update/reset_alt"

# Mentemori
MENTEMORI_BASE_PATH = "https://api.mentemori.icu"
MENTEMORI_WORLD_PATH = "/worlds"
MENTEMORI_TEMPLE_PATH = "/{world_id}/temple/latest"
MENTEMORI_GROUP_PATH = "/wgroups"
MENTEMORI_GACHA_PATH = "/{server_id}/{gacha}/latest"
MENTEMORI_RAID_EVENT_PATH = "/{world_id}/guild_raid/latest"

PLAYER_PATH = "/player/{player_id}"
PLAYER_RANKING_PATH = "/player/ranking"
GUILD_PATH = "/guild/{guild_id}"
GUILD_MEMBERS_PATH = "/guild/{guild_id}/members"
GUILD_RANKING_PATH = "/guild/ranking"