name: Deploy to server

on:
  push:
    branches: [ "main" ]
    paths:
    - aabot/**

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: aabot
  ECR_URL: public.ecr.aws/n7f5u6j0
  ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ID }}:role/aabot_deploy

permissions:
  id-token: write
  contents: read
  
jobs:
  # using ECR as a test and may not be nessecary for this project
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Login to Amazon ECR
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public  
      
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_URL: ${{ env.ECR_URL }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        IMAGE_TAG: latest  # may change later
      run: | 
        docker build -t $ECR_URL/$ECR_REPOSITORY:$IMAGE_TAG ./aabot
        docker push $ECR_URL/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Execute SSH Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ./Artificial-Angel-Bot
          git pull  # probably unneeded due to using ECR
          docker-compose pull  && docker-compose up -d
